//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int Serial { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransType { get; set; }
        public string transRemark { get; set; }
        public decimal Amt { get; set; }
        public string AccNo { get; set; }
    
        public virtual USERinfo USERinfo { get; set; }
    }
}
