//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERinfo
    {
        public USERinfo()
        {
            this.details = new HashSet<detail>();
        }
    
        public string AccNo { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<detail> details { get; set; }
    }
}
